### ISSUE TITLE
Error when converting to onnx

### ISSUE THREAD

**Issue by peymanrostami** [KaenChan/lightqnet#3]
Thank you for the awesome work.

I would like to convert the **lightqnet-dm025.pb** model to **onnx** and then convert the resulted **onnx** file to a **tensorrt** engine. for conversion to **onnx**, I use the following command: 
`python3 -m tf2onnx.convert --saved-model /content/lightqnet/lightqnet-dm025.pb  --opset 16 --output /content/lightqnet/model.onnx`
where `tf2onnx` can be installed from [here](https://github.com/onnx/tensorflow-onnx).

However, after executing this command, I get the following error:

```
/usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2022-06-27 06:21:43,494 - WARNING - '--tag' not specified for saved_model. Using --tag serve
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py", line 696, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py", line 238, in main
    use_graph_names=args.use_graph_names)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/tf_loader.py", line 615, in from_saved_model
    tag, signatures, concrete_function, large_model, use_graph_names)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/tf_loader.py", line 552, in _from_saved_model_v2
    imported = tf.saved_model.load(model_path, tags=tag)  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/load.py", line 936, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/load.py", line 949, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 57, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 116, in parse_saved_model
    f"SavedModel file does not exist at: {export_dir}{os.path.sep}"
OSError: SavedModel file does not exist at: /content/lightqnet/lightqnet-dm025.pb/{saved_model.pbtxt|saved_model.pb}
```

while the address to the `lightqnet-dm025.pb` is correct, I still get the same error. maybe it is happening because the `lightqnet-dm025.pb` file in this repository is  the  .pb file of a **frozen model/graph**, which is different from the .pb file of a **SavedModel**  (and that's why the SavedModel can't be found. Unlike frozen models/graphs, SavedModels are also associated with an auto-generated folder called "variables", which seems to be missing here).

**Could you kindly provide us with the SavedModel version?**

**Comment by HaoLiuHust** [comment]
it's a graphdef format, so use --graphdef
